<div class="content-header">
    <table cellspacing="0"><tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head">Manage Cloudinary Images</h3></td>
            <td class="form-buttons">

                <?php echo $this->getMigrateButton() ?>

                <?php echo $this->getEnableButton() ?>

            </td>
        </tr>
    </tbody></table>
</div>

<p>
    <?php if ($this->allImagesSynced()): ?>
        <div id="messages"><ul class="messages"><li class="notice-msg"><ul><li><span>All images have been successfully migrated to Cloudinary</span></li></ul></li></ul></div>
    <?php else: ?>
        <p>Image migration progress: <?php echo floor($this->getPercentComplete()) ?>%</p>
        <p><?php echo $this->getSynchronizedImageCount() ?> of <?php echo $this->getTotalImageCount() ?> images migrated to Cloudinary.</p>
    <?php endif; ?>
</p>

<p>
    <strong>
        Note: If you have a lot of images (thousands or more), image migration may take a while.
        You can leave this page and come back to check on progress while the migration is performed in the background.
    </strong>
</p>


<p>
    <strong>Looking for more information?</strong> 
    <a href="http://support.cloudinary.com/hc/en-us/sections/200956331-Magento" target="_blank">Visit our Knowledge Base</a>.
</p>

<p>
    <strong>Need assistance or got feedback?</strong> 
    <a href="http://support.cloudinary.com/hc/en-us/requests/new" target="_blank">Contact our support</a>.
</p>
